# Домашнее задание "Библиотека numpy"

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [7]:
import numpy as np

In [21]:
n = 10
array_ = np.arange(n, -1, -1)
array_

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
m_diag = np.diag(array_)
print(m_diag)
print('\nСумма значений на диагонали',sum(np.diag(m_diag)))

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]

Сумма значений на диагонали 55


## Задание 3
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [10]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)

print(f'x = {x[0]}, y = {x[1]}, z = {x[2]}')

# проверка
np.allclose(np.dot(a, x), b)

x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555


True

## Задание 4
Найти самого похожего пользователя

In [11]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [12]:
print('Новый пользователь', list(next_user_stats))

max_cosine = 0
for i, user in enumerate(users_stats):
    cosine = np.dot(user, next_user_stats) / (np.linalg.norm(user) * np.linalg.norm(next_user_stats))
    print(f'Пользователь {i} с покупками {list(user)} имеет косинусное сходство {round(cosine, 3)}')
    
    if cosine > max_cosine:
        max_cosine = cosine
        closest_user_no = i
    
print('Самый похожий пользователь =', closest_user_no)

Новый пользователь [0, 1, 2, 0, 0, 0]
Пользователь 0 с покупками [2, 1, 0, 0, 0, 0] имеет косинусное сходство 0.2
Пользователь 1 с покупками [1, 1, 2, 1, 0, 0] имеет косинусное сходство 0.845
Пользователь 2 с покупками [2, 0, 1, 0, 0, 0] имеет косинусное сходство 0.4
Пользователь 3 с покупками [1, 1, 2, 1, 0, 1] имеет косинусное сходство 0.791
Пользователь 4 с покупками [0, 0, 1, 2, 0, 0] имеет косинусное сходство 0.4
Пользователь 5 с покупками [0, 0, 0, 0, 0, 5] имеет косинусное сходство 0.0
Пользователь 6 с покупками [1, 0, 0, 0, 0, 0] имеет косинусное сходство 0.0
Пользователь 7 с покупками [0, 1, 1, 0, 0, 0] имеет косинусное сходство 0.949
Пользователь 8 с покупками [0, 0, 0, 1, 1, 3] имеет косинусное сходство 0.0
Пользователь 9 с покупками [1, 0, 0, 2, 1, 4] имеет косинусное сходство 0.0
Самый похожий пользователь = 7
